### ISSUE TITLE
CSS常见布局问题

### ISSUE THREAD

**Issue by suoyuesmile** [suoyuesmile/suo-blog#20]

**Comment by suoyuesmile** [comment]
## display
**1. block**
_块级元素，会独立占一行，受height,margin,padding影响_
```html
<!-- 块级元素 -->
<div></div><dir></dir><dl></dl>
<!-- 标题 -->
<h1></h1><h2></h2><h3></h3><h4></h4><h5></h5><h6></h6>
<!-- 段落 -->
<p></p><hr>
<!-- 列表 -->
<ol></ol><ul></ul>
<!-- 表格表单 -->
<table></table><form action=""></form>
<!-- 菜单引用 -->
<menu></menu><blockquote></blockquote>
<!-- 格式化 -->
<pre></pre><center></center>
<!-- h5新增 -->
<head></head><footer></footer><section></section>
```
**2. inline**
_内联元素，不会独占一行，height,width无效，水平方向上margin,padding无效_
```html
<!-- 内联元素 -->
<span></span>
<!-- 字体格式 -->
<b></b><i></i><u></u><em></em><cite></cite><code></code><br>
<!-- 锚 -->
<a href=""></a><q></q><img src="" alt=""><input type="text">
```
**3. 可变元素**
_在不同环境下属性不同_
```html
<!-- 可变元素 -->
<button></button>
<ins></ins><del></del>
<map name=""></map>
```
4**none**
_隐藏，并且不会占用文档空间_

**Comment by suoyuesmile** [comment]
## box model
```css
.main {
	background: #000;
	width: 500px;
	height: 200px;
	margin: 0 auto; 
	max-width: 600px;
}
/*水平居中显示，屏幕变窄后折叠显示*/
.box {
	width: 500px;
	height: 200px;
	margin: 0 auto;
	max-width: 500px;
	border: solid black 1px;
	 -webkit-box-sizing: border-box;
		-mos-box-sizing: border-box;
			-box-sizing: border-box;
}
/*盒子模型，且让padding无法撑大盒子*/
```

**Comment by suoyuesmile** [comment]
## position
**1. static**
_不会被定位，使用top,left等无效_
```css
.demo {
	width: 300px;
	height: 300px;
	left: 30px;
	background: #342;
	position: static;
}	
```
**2. relative**
_同样不会被定位，使用top,left等有效，其他元素不会填补偏离的空隙_
```css
.main {
	width: 300px;
	height: 300px;
	left: 30px;
	background: #342;
	position: relative;
}
```
**3. absolute**
_使用left,top有效，向上级寻找祖先，找到一个非static的定位属性作为父亲，相对父亲定位，如果为找到则父亲为body_
```css
.son {
	width: 300px;
	height: 300px;
	left: 20px;
	background: #666;
	position: absolute;
}
```
**4. fixed**
_top,left有效,相对视窗定位_
```css
.fix {
	width: 300px;
	height: 300px;
	left: 20px;
	background: #666;
	position: fixed;
}
```
**example**
```css
.container {
  position: relative;
}
nav {
  position: absolute;
  left: 0px;
  width: 200px;
}
section {
  /* position is static by default */
  margin-left: 200px;
}
footer {
  position: fixed;
  bottom: 0;
  left: 0;
  height: 70px;
  background-color: white;
  width: 100%;
}
body {
  margin-bottom: 120px;
}
```

**Comment by suoyuesmile** [comment]
## float
**1. what's float**
_浮动的值有4个,none,left,right,inherit,浮动元素会自动添加display:block_

- 脱离正常的文档流，没有脱离文本流，绝对定位都会脱离
- 用于实现文字环绕效果
- 浮动的框可以向左右移动，直到边缘，超出边缘则会转行
```css
img {
	float: right;
	margin: 0 0 1em 1em;
}
```
**2. clear**
_为了解决该元素是紧挨着前面的浮动元素还是移动到它的下方,值both,left,right,none_

```css
.footer {
clear:both;
}
```
- 应用到非浮动元素上时：它将元素的**边框边界**移动到所有相关浮动元素外边界的下方，这时候外边距塌陷不起作用。
- 应用到浮动元素上时：它将元素的**外边界**移动到所有相关浮动元素外边界的下方。这会影响后面浮动元素的布局，后面的浮动元素的位置无法高于它之前的元素。

**3. 容器塌陷**
_如果容器内除了浮动元素外没有其他元素，那么它的高度就会塌陷为0_
- 使用块级上下文解决
- 在容器尾部增加一个伪类来清除浮动
```css
#container:after {
 content: "";
 display: block;
 clear: both;
}
```
4. 清除技巧
- 使用空的div元素
```html
<div style="clear:both;"></div>
```
- 设置overflow:aotu,hidden
```css
img {
  overflow： auto;
}
```
- 利用伪类清除浮动的目的
```css
.clearfix:after {
    content: "";
    visibility: hidden;
    display: block;
    height: 0;
    clear: both
}
```

**Comment by suoyuesmile** [comment]
## Responsive Design
_响应式设计（Responsive Design” 是一种让网站针对不同的浏览器和设备“呈现”不同显示效果的策略，这样可以让网站在任何情况下显示的很棒_
1. media
```css
@media screen and (min-width:600px) {
  nav {
    float: left;
    width: 25%;
  }
  section {
    margin-left: 25%;
  }
}
@media screen and (max-width:599px) {
  nav li {
    display: inline;
  }
}
```

**Comment by suoyuesmile** [comment]
## inline-block
_使用float来铺满浏览器，需要清除浮动才能实现非浮动元素，移动到下面，而使用inline-block实现相同的效果_
```css
/*使用浮动*/
.box {
  float: left;
  width: 200px;
  height: 100px;
  margin: 1em;
}
.after-box {
  clear: left;
}
/*使用inline-block*/
.box2 {
  display: inline-block;
  width: 200px;
  height: 100px;
  margin: 1em;
}
```

**Comment by suoyuesmile** [comment]
## flexbox
_弹性盒子，新的 flexbox 布局模式被用来重新定义CSS中的布局方式。很遗憾的是最近规范变动过多，导致各个浏览器对它的实现也有所不同。_
1. 简单布局
```css
.container {
  display: -webkit-flex;
  display: flex;
}
nav {
  width: 200px;
}
.flex-column {
  -webkit-flex: 1;
          flex: 1;
}
```
2. 牛逼布局
```css
.container {
  display: -webkit-flex;
  display: flex;
}
.initial {
  -webkit-flex: initial;
          flex: initial;
  width: 200px;
  min-width: 100px;
}
.none {
  -webkit-flex: none;
          flex: none;
  width: 200px;
}
.flex1 {
  -webkit-flex: 1;
          flex: 1;
}
.flex2 {
  -webkit-flex: 2;
          flex: 2;
}
```
3. 居中布局
```css
.vertical-container {
  height: 300px;
  display: -webkit-flex;
  display:         flex;
  -webkit-align-items: center;
          align-items: center;
  -webkit-justify-content: center;
          justify-content: center;
}
```
