### ISSUE TITLE
浮动与清除浮动使用场景详解

### ISSUE THREAD

**Issue by suoyuesmile** [suoyuesmile/suo-blog#30]

**Comment by suoyuesmile** [comment]
# 清除浮动
浮动的定义：使元素脱离文档流，遇到父级边界或者相邻元素停止
高度塌陷：浮动元素父元素高度自适应（父元素不写高度，子元素写了浮动，父元素会产生高度塌陷）
# 方法
1. 空div法
```css
{
clear:both;
height:0;
overflow:hidden;
}
```
2. 给父级元素设置高度(浮动元素高度不确定的时候不行)
3. 父级元素也浮动（浮动太多导致问题）
4. 父级设置为inline-block
5. 使用换行符清除浮动（不符合结构和样式分类原则）
6. 给父级元素增加overflow:hidden（兼容IE6,7，配合zoom）
7. after伪类清除浮动(常用,zoom)
